In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Multimodal Personality-Driven Career Intelligence System\data\personality_dataset\mbti_1.csv")

print(df.shape)

(8675, 2)

In [3]:
df.head()

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [4]:
import re

def clean_text(text):
    
    # Split posts separated by |||
    text = text.replace("|||", " ")

    # Remove links
    text = re.sub(r"http\S+", "", text)

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove special characters
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # Lowercase
    text = text.lower()

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [5]:
df["clean_posts"] = df["posts"].apply(clean_text)

In [6]:
df[["posts", "clean_posts"]].head()

,posts,clean_posts
0,'http://www.youtube.com/watch?v=qsXHcwe3krw|||...,enfp and intj moments sportscenter not top ten...
1,'I'm finding the lack of me in these posts ver...,im finding the lack of me in these posts very ...
2,'Good one _____ https://www.youtube.com/wat...,good one of course to which i say i know thats...
3,"'Dear INTP, I enjoyed our conversation the o...",dear intp i enjoyed our conversation the other...
4,'You're fired.|||That's another silly misconce...,youre fired thats another silly misconception ...

In [7]:
df["type"].value_counts()

type
INFP    1832
INFJ    1470
INTP    1304
INTJ    1091
ENTP     685
ENFP     675
ISTP     337
ISFP     271
ENTJ     231
ISTJ     205
ENFJ     190
ISFJ     166
ESTP      89
ESFP      48
ESFJ      42
ESTJ      39
Name: count, dtype: int64

In [8]:
df = df[df["type"].isin(top_types)]

NameError: name 'top_types' is not defined

In [9]:
top_types = [
    "INFP", "INFJ", "INTP", "INTJ",
    "ENTP", "ENFP", "ISTP", "ISFP"
]

In [10]:
df = df[df["type"].isin(top_types)]

In [11]:
df["type"].value_counts()

type
INFP    1832
INFJ    1470
INTP    1304
INTJ    1091
ENTP     685
ENFP     675
ISTP     337
ISFP     271
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["label"] = le.fit_transform(df["type"])

In [14]:
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(label_mapping)

{'ENFP': np.int64(0), 'ENTP': np.int64(1), 'INFJ': np.int64(2), 'INFP': np.int64(3), 'INTJ': np.int64(4), 'INTP': np.int64(5), 'ISFP': np.int64(6), 'ISTP': np.int64(7)}

In [15]:
df[["type", "label"]].head()

   type  label
0  INFJ      2
1  ENTP      1
2  INTP      5
3  INTJ      4
5  INTJ      4